### ISSUE TITLE
sonic-visualizer: Missing dependency on libmad0-dev and qmake

### ISSUE THREAD

**Issue by subwire** [zardus/ctf-tools#10]
.

**Comment by zardus** [comment]
Can you check if it's fixed in bee03c5?

**Comment by subwire** [comment]
Nope -- was missing more stuff, including QDebug.h and asound.h... looks
like you also need libqt4-dev and libasound2-dev
... but that doesn't fix it either, because 14.04's qt4 is too old.  The
issue got fixed upstream (they removed that part) but if you clone from hg
there are other issues.

But they do offer ubuntu packages, and they're newer than what's in APT.
Backup plan?

**Comment by zardus** [comment]
Oh, wow. I totally missed that it was already in apt. I probably spelled it "visualizer" when searching for it :-).

Are you sure it uses QT4 and not QT5?

If it's in apt, and the apt version is decently new, we should probably just use that one, and/or their deb. That's probably outside of the scope of this repo, though

**Comment by subwire** [comment]
either/or, doesn't matter to me.
Tested their deb and it works
- E
